Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kglobalaccel': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'plasma/plasma-framework': '@same'
    'plasma/plasma5support': '@same'

Options:
  require-passing-tests-on: [ '@all' ]
