Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kglobalaccel': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/plasma-framework': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kcmutils': '@stable'
