Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kglobalaccel': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/plasma-framework': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/kio': '@stable'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kglobalaccel': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/plasma-framework': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'plasma/plasma5support': '@latest-kf6'

Options:
  require-passing-tests-on: [ '@all' ]
